openapi: 3.0.3
info:
  title: Drug Interactions API
  version: "1.0"
paths:
  /interactions:
    get:
      operationId: drug_interactions_lookup
      summary: Check interactions for a list of drug names
      parameters:
        - in: query
          name: drugs
          required: true
          schema:
            type: array
            items: { type: string }
          style: form
          explode: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  interactions:
                    type: array
                    items:
                      type: object
                      properties:
                        pair: { type: string }
                        severity: { type: string }
                        note: { type: string }
